title: David Hill
author: DavidMarkHill
email: davidmarkhill@outlook.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://davidmarkhill.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  davidmarkhill
instagram_username: david_109_9
facebook_username: Davidhill25
linkedin_username: david-hill-90528610b
bitbucket_username: DavidMarkHill
social:
  name: David Hill
  links:
    - https://www.facebook.com/Davidhill25
    - https://www.linkedin.com/in/david-hill-90528610b
    - https://github.com/davidmarkhill

disqus:
  shortname: davidhill # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
